---
abstract: 'Perl extension for managing Search Engine Sitemaps'
author:
  - 'Jason Kohles <email@jasonkohles.com>'
build_requires:
  DateTime: '0'
  File::Copy: '0'
  HTTP::Date: '0'
  HTTP::Response: '0'
  Test::Mock::LWP::UserAgent: '0'
  Test::Most: '0'
  ok: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-Sitemap
requires:
  Carp: '0'
  Class::Load: '0'
  Class::Trigger: '0'
  HTML::Entities: '0'
  IO::File: '0'
  LWP::UserAgent: '0'
  Module::Find: '0'
  Moose: '0'
  MooseX::ClassAttribute: '0'
  MooseX::Types: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::URI: '0'
  POSIX: '0'
  Scalar::Util: '0'
  URI: '0'
  XML::Twig: '0'
  namespace::clean: '0'
  perl: '5.008003'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Search-Sitemap
  repository: https://github.com/neilbowers/Search-Sitemap.git
version: 2.13_01
